### ISSUE TITLE
fun commands should not require prefix

### ISSUE THREAD

**Issue by SuKiN-a** [UnknownAuthority/Actual-Working-Better-DS-bot#10]
currently fun commands require prefix to run (ie ?hewwo, ?quote), this shouldn't be the case since the whole reason the fun commands are fun is because they aren't triggered manually.

**Comment by SuKiN-a** [comment]
there does not seem to be a way to do this in discord.py without restructuring the whole bot, so it seems that the best way will be to make a separate bot that logs into the same account and takes care of the fun commands

**Comment by ghost** [comment]
> there does not seem to be a way to do this in discord.py without restructuring the whole bot, so it seems that the best way will be to make a separate bot that logs into the same account and takes care of the fun commands

Yeah no, we could just do a on_message in Fun.py and it'll be done
Since there's so much demand I'll add them back

**Comment by SuKiN-a** [comment]
the current implementation does not work like intended, ie they only trigger when the command is used and not when a message that contains the phrase is used
ie hewwo there wont trigger the bot even tho that is the intended behavior

**Comment by ghost** [comment]
Resolved
